dist: focal
language: minimal

before_install:
  - sudo add-apt-repository -y ppa:live-build/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install live-build debian-archive-keyring debian-keyring

addons:
  artifacts: true
  paths:
    - /var/www/html/initrd.img
    - /var/www/html/vmlinuz
    - /var/www/html/filesystem.squashfs

branches:
  only:
  - feature/bullseye-fvwm

script:
  - export DIR=/srv/live-build-x2go-`date +"%Y%m%d%H%M%S"`
  - sudo mkdir $DIR /var/www/html
  - cd $DIR
  - sudo lb config -d bullseye --chroot-filesystem squashfs --apt-indices false --cache-packages false --config git://code.x2go.org/live-build-x2go.git::feature/bullseye-fvwm --archive-areas "main contrib non-free" --apt-recommends false --firmware-binary false --updates true --backports false --win32-loader false --loadlin false --security false  --initsystem systemd  -b netboot --bootappend-live aufs vconsole.keymap=de-latin1-nodeadkeys kernel.sysrq=1 sysrq_always_enabled log_buf_len=1M quickreboot silent splash lang=de locales=de_DE.UTF-8 keyboard-layouts=de consoleblank=0 quiet keep_bootcon toram live-config live-config.timezone=Europe/Berlin
  - sudo lb build
  - cd `dirname $DIR`
  - ln -nfs `basename $DIR` lb-x2go
  - cd /var/www/html
  - ln -nfs /srv/lb-x2go/tftpboot/live/initrd.img .
  - ln -nfs /srv/lb-x2go/tftpboot/live/vmlinuz .
  - ln -nfs /srv/lb-x2go/binary/live/filesystem.squashfs .
