#!/bin/sh
# inject screen blanking/unblanking script into initrd

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

if [ ! -x "../../lib/live/config/0000-earlyblankdpmsfix" ]; then
        exit 0
fi

# for some silly reason, this file is needed in two places
sed \
	-e 's#/bin/bash#/bin/sh#' \
	-e '/^echo -n/d' \
	-e 's/early/initrd/g' \
	-e 's/Early/Initrd/g' \
../../lib/live/config/0000-earlyblankdpmsfix >"${DESTDIR}/lib/live/boot/0000-initrdblankdpmsfix"
cp "${DESTDIR}/lib/live/boot/0000-initrdblankdpmsfix" "${DESTDIR}/bin/boot/0000-initrdblankdpmsfix"
chmod 755 "${DESTDIR}/lib/live/boot/0000-initrdblankdpmsfix" "${DESTDIR}/bin/boot/0000-initrdblankdpmsfix"
echo "HEREHEREHERE"
ls -lah "${DESTDIR}"
echo "XXXXXX"
ls -lah "${DESTDIR}/lib/"
echo "XXXXXX"
ls -lah "${DESTDIR}/lib/live/"
echo "XXXXXX"
ls -lah "${DESTDIR}/lib/live/boot/"
echo "XXXXXX"
ls -lah "${DESTDIR}/bin/"
echo "XXXXXX"
ls -lah "${DESTDIR}/bin/boot/"
echo "HEREHEREHERE"
exit 0
