#!/bin/bash

WaitForVTs ()
{

# Output startup message
#
echo -n " waitforvts"

cat >/etc/network/if-up.d/0000-waitforvts <<SHOWIPS
#!/bin/bash
export TERM=linux;

# wait until terminal is available
while ! [ -c /dev/tty$(fgconsole -n) ] ; do
	echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for an unused VT to become available."
	sleep 2
done

chmod 755 /etc/network/if-up.d/0000-waitforvts

}

WaitForVTs
