#!/bin/bash

ShowIFConfig ()
{

# Output startup message
#
echo -n " showifconfig"

#setterm -term linux -r >/dev/tty9
# Make sure no language-specific stuff interferes with our matching
# grep: highlight everything that matches "inet" to the end of its line
# and also (-E, |$) show every line that has an end => Everything else
# Output the result on virtual terminal 9
cat >/etc/network/if-up.d/showips <<SHOWIPS
#!/bin/bash
export TERM=linux;

ip -c a >> /etc/issue; 
ip -c a >> /etc/issue.net 
SHOWIPS

chmod 755 /etc/network/if-up.d/showips

}

ShowIFConfig
