#!/bin/sh

GetSSHPubKeysFromServer ()
{

    # Output startup message
    #
    echo -n " getsshpubkeysfromserver"


    PUBKEYURL=$(cat /proc/cmdline | \
            tr ' ' '\n' | \
            awk -F'=' ' /^pubkey=/ { print $2 }')

    if [ -n "$PUBKEYURL" ] ; then
        cat >/etc/network/if-up.d/getsshpubkeysfromserver <<GETPUBKEY
#!/bin/bash
export TERM=linux;

while ! ip a | grep -v "inet 127.0.0.1" | grep -v "inet6 ::1/128" | grep -q inet ; do
        sleep 2
done

# Set Keyfile
#
mkdir -p /root/.ssh
chmod 600 /root/.ssh
touch /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys

if echo "$PUBKEY" | grep -q "^tftp://" ; then
    PUBKEYSERVER=$(echo "$PUBKEYURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
    PUBKEYPATH=$(echo "$PUBKEYURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
    if [ -n "$PUBKEYSERVER" ] && [ -n "$PUBKEYPATH" ] ; then
        while ! atftp $PUBKEYSERVER -g -r $PUBKEYPATH -l /root/.ssh/authorized_keys ; do
            echo "Waiting for SSH Public Key ..."
            sleep 5
        done
    fi
else
    while ! wget -q -O - $PUBKEYURL >>/root/.ssh/authorized_keys ; do
        echo "Waiting for SSH Public Key ..."
        sleep 5
    done
fi
GETPUBKEY

        chmod 755 /etc/network/if-up.d/getsshpubkeysfromserver
    fi

}

GetSSHPubKeysFromServer

