#!/bin/bash

AddUser2TTY ()
{

# Output startup message
#
echo -n " adduser2tty"

# this is so that we can log to tty8 (status) and tty9 (debug)
if [ -n "$(getent passwd user 2>/dev/null)" ] ; then
	adduser user tty
elif [ -n "$(getent passwd x2gothinclient 2>/dev/null)" ] ; then
	adduser x2gothinclient tty
else
	: # NOP
fi

}

AddUser2TTY
