#!/bin/sh

GetSSHPubKeysFromServer ()
{

	# Output startup message
	#
	echo -n " getsshpubkeysfromserver"


	PUBKEYURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		    awk -F'=' ' /^pubkey=/ { print $2 }' |\
		    tr -dc 'a-zA-Z0-9.:/?%_\-')

	if [ -n "$PUBKEYURL" ] ; then
		cat >/etc/network/if-up.d/0200-getsshpubkeysfromserver <<GETPUBKEY
#!/bin/bash
export TERM=linux;

if [ "\$METHOD" = "loopback" ] || [ "\$METHOD" = "none" ]; then
        exit 0
fi

(
	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done
	while [ -z "\$(hostname -I)" ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8
		sleep 2
	done

	# Set Keyfile
	#
	mkdir -p /root/.ssh
	chmod 600 /root/.ssh
	touch /root/.ssh/authorized_keys
	chmod 600 /root/.ssh/authorized_keys

	echo -en "\n\$(date +'%F | %T | ')'\$0': Attempting SSH public keyfile download ..." | tee -a /dev/tty8
	if echo "$PUBKEYURL" | grep -q "^tftp://" ; then
		PUBKEYSERVER=$(echo "$PUBKEYURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
		PUBKEYPATH=$(echo "$PUBKEYURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
		if [ -n "\$PUBKEYSERVER" ] && [ -n "\$PUBKEYPATH" ] ; then
			while ! atftp "\$PUBKEYSERVER" -g -r "\$PUBKEYPATH" -l /root/.ssh/authorized_keys ; do
				echo -en "\n\$(date +'%F | %T | ')'\$0': still waiting for download (tftp) ..." | tee -a /dev/tty8
				sleep 5
			done
		fi
	else
		while ! wget -q -O - "$PUBKEYURL" >/root/.ssh/authorized_keys ; do
			echo -en "\n\$(date +'%F | %T | ')'\$0': still waiting for download (wget) ..." | tee -a /dev/tty8
			sleep 5
		done
	fi
	echo -en "\n\$(date +'%F | %T | ')'\$0': SSH public keyfile download complete." | tee -a /dev/tty8
) &
GETPUBKEY

		chmod 755 /etc/network/if-up.d/0200-getsshpubkeysfromserver
	fi

}

GetSSHPubKeysFromServer

