#!/bin/sh

XServerXorgGetXorgConf ()
{
# Output startup message
#
echo -n " xserver-xorg-getxorgconf"

        XORGCONFURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' /proc/cmdline | \
                      awk -F'=' ' /^xorgconfurl=/ { print $2 }' | \
		      tr -dc 'a-zA-Z0-9.:/?%_\-')
        if [ -n "$XORGCONFURL" ] && [ -d /etc/X11 ] ; then 
		XORGCONFDESTINATION=/etc/X11/xorg.conf.new
	        cat >/etc/network/if-up.d/0300-getxorgconf <<GETXORG
#!/bin/bash
export TERM=linux;

if [ "\$METHOD" = "loopback" ] || [ "\$METHOD" = "none" ]; then
        exit 0
fi

(
	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done
	while [ -z "\$(hostname -I)" ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8
		sleep 2
	done

	echo -en "\n\$(date +'%F | %T | ')'\$0': Attempting xorg.conf download ..." | tee -a /dev/tty8
	if echo "$XORGCONFURL" | grep -q "^tftp://" ; then
		XORGCONFSERVER=$(echo "$XORGCONFURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
		XORGCONFPATH=$(echo "$XORGCONFURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
		if [ -n "\$XORGCONFSERVER" ] && [ -n "\$XORGCONFPATH" ] ; then
			while ! atftp "\$XORGCONFSERVER" -g -r "\$XORGCONFPATH" -l $XORGCONFDESTINATION ; do
				echo -en "\n\$(date +'%F | %T | ')'\$0': still waiting for xorg.conf download (tftp) ..." | tee -a /dev/tty8
				sleep 5
			done
		fi
	else
		while ! wget -q -O $XORGCONFDESTINATION "$XORGCONFURL" ; do
			echo -en "\n\$(date +'%F | %T | ')'\$0': still waiting for xorg.conf download (wget) ..." | tee -a /dev/tty8
			sleep 5 
		done
	fi

	echo -en "\n\$(date +'%F | %T | ')'\$0': xorg.conf download complete." | tee -a /dev/tty8

	if [ -s $XORGCONFDESTINATION ] ; then
		mv $XORGCONFDESTINATION /etc/X11/xorg.conf
	fi
) &
GETXORG
                chmod 755 /etc/network/if-up.d/0300-getxorgconf
        fi
}
XServerXorgGetXorgConf
