#!/bin/sh

XServerXorgGetXorgConf ()
{
# Output startup message
#
echo -n " xserver-xorg-getxorgconf"

        XORGCONFURL=$(cat /proc/cmdline | \
                       tr ' ' '\n' | \
                       awk -F'=' ' /^xorgconfurl=/ { print $2 }')
        if [ -n "$XORGCONFURL" ] && [ -d /etc/X11 ] ; then 
		XORGCONFDESTINATION=/etc/X11/xorg.conf.new
	        cat >/etc/network/if-up.d/0300-getxorgconf <<GETXORG
#!/bin/bash
export TERM=linux;

while ! [ -s /var/run/availablevt ] ; do
	echo -en "\n'\$0' is waiting for a free console."
	sleep 2
done

while [ -z "\$(hostname -I)" ] ; do
	echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty\$(cat /var/run/availablevt)
	sleep 2
done
if echo "$XORGCONFURL" | grep -q "^tftp://" ; then
	XORGCONFSERVER=$(echo "$XORGCONFURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
	XORGCONFPATH=$(echo "$XORGCONFURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
	if [ -n "\$XORGCONFSERVER" ] && [ -n "\$XORGCONFPATH" ] ; then
		while ! atftp \$XORGCONFSERVER -g -r \$XORGCONFPATH -l $XORGCONFDESTINATION ; do
			echo -en "\n\$(date +'%F | %T | ')'\$0': Waiting for xorg.conf download ..." | tee -a /dev/tty\$(cat /var/run/availablevt)
			sleep 5
		done
	fi
else
	while ! wget -q -O $XORGCONFDESTINATION $XORGCONFURL ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0': Waiting for xorg.conf download ..." | tee -a /dev/tty\$(cat /var/run/availablevt)
		sleep 5 
	done
fi

if [ -s $XORGCONFDESTINATION ] ; then
	mv $XORGCONFDESTINATION /etc/X11/xorg.conf
fi
GETXORG
                chmod 755 /etc/network/if-up.d/0300-getxorgconf
        fi
}
XServerXorgGetXorgConf
