#!/bin/sh


X2GoGetOpenSSHKey ()
{
# Output startup message
#
echo -n " x2go-getopensshkey"

# This script is for using the iso-hybrid image along with the "second partition" patch
# it allows you to share ssh secret keys between X2GoClient for Windows in portable
# mode and the X2Go-ThinClientEnvironment on the same USB media using different partitions

# Homedir des clientseitigen X2Go-ThinClient-Accounts
#
X2GOHOME="/var/lib/x2gothinclient/"

# Homedir der Portable-App-Installation
#
HOME="/media/PORTABLEAPP/"

# .ssh-Directory anlegen, das existiert zu diesem Zeitpunkt noch nicht
#
mkdir -p $(readlink -m "$X2GOHOME/.ssh/")

for KEYFILE in $HOME/ssh/* ; do
	[ -s "$KEYFILE" ] || continue
	KEYDESTPATH="$X2GOHOME/.ssh/$(basename "$KEYFILE")"
	touch "$KEYDESTPATH"
	chown   x2gothinclient:x2gothinclient \
		$KEYDESTPATH
	chmod   600 $KEYDESTPATH
	cat     $(readlink -m "$KEYFILE")>$KEYDESTPATH

done

ln -s $X2GOHOME/.ssh $X2GOHOME/ssh

}

X2GoGetOpenSSHKey

