#!/bin/sh


X2GoGetOpenSSHPortableClientKey ()
{
	# Output startup message
	#
	echo -n " x2go-getopensshportableclientkey"

	# This script is for using the iso-hybrid image along with the "second partition" patch
	# it allows you to share ssh secret keys between X2GoClient for Windows in portable
	# mode and the X2Go-ThinClientEnvironment on the same USB media using different partitions

	# Homedir of client side X2Go ThinClient Account
	#
	X2GOHOME="/home/user/"

	# Homedir of Portable App Installation
	#
	HOME="/media/PORTABLEAPP/"

	if [ -d "$HOME" ] && [ -d "$X2GOHOME" ]; then

		# create .ssh-Directory in case it doesn't exist
		#
		mkdir -p $(readlink -m "$X2GOHOME/.ssh/")

		for KEYFILE in $HOME/ssh/* ; do
			[ -s "$KEYFILE" ] || continue
			KEYDESTPATH="$X2GOHOME/.ssh/$(basename "$KEYFILE")"
			touch "$KEYDESTPATH"
			chown   user:user \
				$KEYDESTPATH
			chmod   600 $KEYDESTPATH
			cat     $(readlink -m "$KEYFILE")>$KEYDESTPATH

		done

		# this is so the path name in the sessions file matches again
		# (cannot use .ssh on FAT, for example)
		ln -s $X2GOHOME/.ssh $X2GOHOME/ssh
	fi
}

X2GoGetOpenSSHPortableClientKey

