#!/bin/bash

TcpPrint ()
{

# Output startup message
#
echo -n " tcpprint"

if grep -q "\W*tcpprint\W*" /proc/cmdline ; then

        TCPPRINTONLYFROM=$(cat /proc/cmdline | \
                       sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
                       awk -F'=' ' /^tcpprintonlyfrom=/ { print $2 }' | \
		       tr -dc 'a-zA-Z0-9.\-')
	if [ -n "$TCPPRINTONLYFROM" ] ; then
		TCPPRINTONLYFROM="only_from = $TCPPRINTONLYFROM"
	fi
	# Backgrounding
	(

	while ! lsmod | grep -q "^lp"; do
		# Wait till modprobe lp has occurred
		# -> this means /dev is fully populated
		# => USB-Printers can be detected now, too
		sleep 30
	done

	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done

	PRINTERDEVICES=""
	[ -d /dev/usb ] && PRINTERDEVICES=$(find /dev/usb -type c -name "lp*" | sort)
	PRINTERDEVICES="$PRINTERDEVICES $(find /dev/ -maxdepth 1 -type c -name "lp*" | sort)"

	echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8

	# Create a listening port for a TCP/9100-RAW-printer
	#
	# printers may be at /dev/lp_ and at /dev/usb/lp_
	PRINTERCOUNT=0
	for PRINTERDEV in $PRINTERDEVICES; do 
		PORTNUMBER=$((PRINTERCOUNT+9100))
		echo "jetdirect${PRINTERCOUNT} ${PORTNUMBER}/tcp" >>/etc/services
		cat >/etc/xinetd.d/jetdirect${PRINTERCOUNT} << JETDIRCONF 
service jetdirect${PRINTERCOUNT}
{
	socket_type = stream
	protocol = tcp
	wait = no
	user = root
	server = /bin/dd
	server_args = of=$PRINTERDEV bs=1024k
	groups = yes
	disable = no
	instances = 1
	$TCPPRINTONLYFROM
}
JETDIRCONF
		echo -en "\n\$(date +'%F | %T | ')Mapping $PRINTERDEV => $PORTNUMBER" | tee -a /dev/tty8
		PRINTERCOUNT=$((PRINTERCOUNT+1))
	done

	echo "#Local printer config: Done." >/etc/xinetd.d/jetdirect

	if ps -C xinetd --no-header >/dev/null ; then
		echo -en "\n\$(date +'%F | %T | ')xinetd needs to be restarted, trying to do that ..." | tee -a /dev/tty8
		if /etc/init.d/xinetd restart; then
			echo -n " success. All done." | tee -a /dev/tty8
		else
			echo -n " error." | tee -a /dev/tty8
		fi
	else
		echo -en "\n\$(date +'%F | %T | ')No xinetd restart necessary. All done." | tee -a /dev/tty8
	fi

	) &
fi
}

TcpPrint
