#!/bin/sh

X2GoGetSessions ()
{
	# Output startup message
	#
	echo -n " x2go-getsessions"

	SESSIONSURL=$(cat /proc/cmdline | \
		       tr ' ' '\n' | \
		       awk -F'=' ' /^sessionsurl=/ { print $2 }')
	if [ -n "$SESSIONSURL" ] && [ -d /etc/x2go ] ; then 
		# only mv this file if SESSIONSURL was set. If not, leave it in place - as
                # it might have been customized at image creation time
        	mv /etc/x2go/x2gothinclient_sessions /etc/x2go/x2gothinclient_sessions_old
		SESSIONSDESTINATION=/etc/x2go/x2gothinclient_sessions_new
		cat >/etc/network/if-up.d/030-getsessions <<GETSESS
#!/bin/bash
export TERM=linux;

(
	while [ -z "\$(hostname -I)" ] ; do
		echo "'\$0' is waiting for a client IP."
		sleep 2
	done
	if echo "$SESSIONSURL" | grep -q "^tftp://" ; then
		SESSIONSSERVER=$(echo "$SESSIONSURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
		SESSIONSPATH=$(echo "$SESSIONSURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
		if [ -n "$SESSIONSSERVER" ] && [ -n "$SESSIONSPATH" ] ; then
			while ! atftp $SESSIONSSERVER -g -r $SESSIONSPATH -l $SESSIONSDESTINATION ; do
				echo "Waiting for session config data ..."
				sleep 5
			done
		fi
	else
		while ! wget -q -O $SESSIONSDESTINATION $SESSIONSURL ; do
			echo "Waiting for session config data ..."
			sleep 5 
		done
	fi

	if [ -s $SESSIONSDESTINATION ] ; then
		mv $SESSIONSDESTINATION /etc/x2go/x2gothinclient_sessions
	fi
) &
GETSESS
		chmod 755 /etc/network/if-up.d/030-getsessions
	fi
}

X2GoGetSessions
