#!/bin/sh

X2GoGetSessions ()
{
	# Output startup message
	#
	echo -n " x2go-getsessions"

	SESSIONSURL=$(cat /proc/cmdline | \
		       sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
		       awk -F'=' ' /^sessionsurl=/ { print $2 }' | \
		       tr -dc 'a-zA-Z0-9.:/?%_\-')
	if [ -n "$SESSIONSURL" ] && [ -d /etc/x2go ] ; then 
		# only mv this file if SESSIONSURL was set. If not, leave it in place - as
                # it might have been customized at image creation time
        	mv /etc/x2go/x2gothinclient_sessions /etc/x2go/x2gothinclient_sessions_old
		SESSIONSDESTINATION=/etc/x2go/x2gothinclient_sessions_new
		cat >/etc/network/if-up.d/0400-getsessions <<GETSESS
#!/bin/bash
export TERM=linux;

if [ "\$METHOD" = "loopback" ] || [ "\$METHOD" = "none" ]; then
        exit 0
fi

(
	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done
	while [ -z "\$(hostname -I)" ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8
		sleep 2
	done

	echo -en "\n\$(date +'%F | %T | ')'\$0': Attempting session config data download ..." | tee -a /dev/tty8
	if echo "$SESSIONSURL" | grep -q "^tftp://" ; then
		SESSIONSSERVER=$(echo "$SESSIONSURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
		SESSIONSPATH=$(echo "$SESSIONSURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
		if [ -n "\$SESSIONSSERVER" ] && [ -n "\$SESSIONSPATH" ] ; then
			while ! atftp "\$SESSIONSSERVER" -g -r "\$SESSIONSPATH" -l $SESSIONSDESTINATION ; do
				echo -en "\n\$(date +'%F | %T | ')still waiting for session config data (tftp) ..." | tee -a /dev/tty8
				sleep 5
			done
		fi
	else
		while ! wget -q -O $SESSIONSDESTINATION "$SESSIONSURL" ; do
			echo -en "\n\$(date +'%F | %T | ')still waiting for session config data (wget) ..." | tee -a /dev/tty8
			sleep 5 
		done
	fi

	echo -en "\n\$(date +'%F | %T | ')'\$0': session config data download complete." | tee -a /dev/tty8
	if [ -s $SESSIONSDESTINATION ] ; then
		mv $SESSIONSDESTINATION /etc/x2go/x2gothinclient_sessions
	fi
) &
GETSESS
		chmod 755 /etc/network/if-up.d/0400-getsessions
	fi
}

X2GoGetSessions
