#!/bin/sh

X2GoGetBranding ()
{
	# Output startup message
	#
	echo -n " x2go-getbranding"


	BRANDINGURL=$(cat /proc/cmdline | \
		       tr ' ' '\n' | \
		       awk -F'=' ' /^branding=/ { print $2 }')
	BRANDINGDESTINATION=/etc/x2go/branding.svg

	if [ -n "$BRANDINGURL" ] ; then
		cat >/etc/network/if-up.d/0410-getbranding <<GETBRAND
#!/bin/bash
export TERM=linux;

if [ "\$METHOD" = "loopback" ] || [ "\$METHOD" = "none" ]; then
        exit 0
fi

(
	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done
	while [ -z "\$(hostname -I)" ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8
		sleep 2
	done

	echo -en "\n\$(date +'%F | %T | ')'\$0': Attempting branding SVG download ..." | tee -a /dev/tty8
	if echo "$BRANDINGURL" | grep -q "^tftp://" ; then
		BRANDINGSERVER=$(echo "$BRANDINGURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
		BRANDINGPATH=$(echo "$BRANDINGURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
		if [ -n "\$BRANDINGSERVER" ] && [ -n "\$BRANDINGPATH" ] ; then
			while ! atftp \$BRANDINGSERVER -g -r \$BRANDINGPATH -l ${BRANDINGDESTINATION}.tmp ; do
				echo -en "\n\$(date +'%F | %T | ')still waiting for branding SVG download (tftp) ..." | tee -a /dev/tty8
				sleep 5
			done
		fi
	else
		while ! wget -q -O ${BRANDINGDESTINATION}.tmp $BRANDINGURL ; do
			echo -en "\n\$(date +'%F | %T | ')still waiting for branding SVG download (wget) ..." | tee -a /dev/tty8
			sleep 5 
		done
	fi

	echo -en "\n\$(date +'%F | %T | ')'\$0': branding SVG download complete." | tee -a /dev/tty8
	if ! [ -s ${BRANDINGDESTINATION}.tmp ] ; then
		mv ${BRANDINGDESTINATION}.tmp $BRANDINGDESTINATION
	fi
) &
GETBRAND
		chmod 755 /etc/network/if-up.d/0410-getbranding
	fi
}

X2GoGetBranding
