#!/bin/sh

X2GoGetBG ()
{
	# Output startup message
	#
	echo -n " x2go-getbg"


	BGURL=$(cat /proc/cmdline | \
		       tr ' ' '\n' | \
		       awk -F'=' ' /^bg=/ { print $2 }')
	BGDESTINATION=/etc/x2go/bg.svg

	if [ -n "$BGURL" ] ; then
		cat >/etc/network/if-up.d/0420-getbg <<GETBG
#!/bin/bash
export TERM=linux;

if [ "\$METHOD" = "loopback" ] || [ "\$METHOD" = "none" ]; then
        exit 0
fi

(
	while ! [ -c /dev/tty8 ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for tty8 to become available."
		sleep 2
	done
	while [ -z "\$(hostname -I)" ] ; do
		echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty8
		sleep 2
	done

	echo -en "\n\$(date +'%F | %T | ')'\$0': Attempting background SVG download ..." | tee -a /dev/tty8
	if echo "$BGURL" | grep -q "^tftp://" ; then
		BGSERVER=$(echo "$BGURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
		BGPATH=$(echo "$BGURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
		if [ -n "\$BGSERVER" ] && [ -n "\$BGPATH" ] ; then
			while ! atftp \$BGSERVER -g -r \$BGPATH -l ${BGDESTINATION}.tmp ; do
				echo -en "\n\$(date +'%F | %T | ')still waiting for background SVG download (tftp) ..." | tee -a /dev/tty8
				sleep 5
			done
		fi
	else
		while ! wget -q -O ${BGDESTINATION}.tmp $BGURL ; do
			echo -en "\n\$(date +'%F | %T | ')still waiting for background SVG download (wget) ..." | tee -a /dev/tty8
			sleep 5 
		done
	fi

	echo -en "\n\$(date +'%F | %T | ')'\$0': background SVG download complete." | tee -a /dev/tty8
	if [ -s ${BGDESTINATION}.tmp ] ; then
		mv ${BGDESTINATION}.tmp $BGDESTINATION
	fi
) &
GETBG
		chmod 755 /etc/network/if-up.d/0420-getbg
	fi
}

X2GoGetBG
