#!/bin/sh

X2GoPowerbuttonMonitor ()
{
# Output startup message
#
echo -n " x2go-powerbuttonmonitor"

# Spawn Powerbutton-Monitor
/bin/bash -c '(while ! [ -f /home/user/.halt ] ; do sleep 1 ; done ; poweroff ; chvt 7) &'
}

X2GoPowerbuttonMonitor
