#!/bin/bash

X2GoThinClientConfig ()
{

# Output startup message
#
echo -n " x2go-thinclientconfig"

sed -i -e '\#<applications>#a<application title="X2Go Client" type="normal">' -e '\#<applications>#a<decor>no</decor>' -e '\#<applications>#a</application>' /etc/xdg/openbox/rc.xml

cat >/home/user/.xsession <<XSESSION
# inspired by 
# http://code.x2go.org/gitweb?p=x2gothinclient.git;a=blob_plain;f=displaymanager/sbin/x2gothinclientd;h=6897d42d17bd6778e7de5e62ec3f51727d4e8800;hb=HEAD
# check the above file for ideas before reinventing the wheel

# Spawn PulseAudio
pulseaudio -D -n -L 'module-native-protocol-tcp port=4713' -L 'module-udev-detect' --exit-idle-time=65535 &

# Spawn openbox
openbox &


# Get X2GoConfig
BROKERURL=\$(cat /proc/cmdline | \
	    tr ' ' '\n' | \
	    awk -F'=' ' /^broker-url=/ { print \$2 }')
LDAP=\$(cat /proc/cmdline | \
	    tr ' ' '\n' | \
	    sed 's/^ldap=/ldap#/' | \
	    awk -F'#' ' /^ldap#/ { print \$2 }')
LDAP1=\$(cat /proc/cmdline | \
	    tr ' ' '\n' | \
	    sed 's/^ldap1=/ldap1#/' | \
	    awk -F'#' ' /^ldap1#/ { print \$2 }')
LDAP2=\$(cat /proc/cmdline | \
	    tr ' ' '\n' | \
	    sed 's/^ldap2=/ldap2#/' | \
	    awk -F'#' ' /^ldap2#/ { print \$2 }')

# Spawn X2GoClient
if [ -n "\$BROKERURL" ]; then
	SESSIONFROM="--broker-url=\$BROKERURL"
else 
	SESSIONFROM="--session-conf=/etc/x2go/x2gothinclient_sessions"
fi
if [ -n "\$LDAP" ] ; then
	if [ -n "\$LDAP1" ] ; then
		BACKUPLDAP="--ldap1=\$LDAP1"
		if [ -n "\$LDAP2" ] ; then
			BACKUPLDAP="\$BACKUPLDAP --ldap2=\$LDAP2"
		fi
	fi
	LDAPPARAMS="--ldap=\$LDAP \$BACKUPLDAP"
else
	LDAPPARAMS=""
fi
 
x2goclient --thinclient --no-session-edit --no-menu --maximize --add-to-known-hosts --haltbt \$LDAPPARAMS \$SESSIONFROM
XSESSION

chown user:user /home/user/.xsession
chmod 644 /home/user/.xsession

}

X2GoThinClientConfig
