#!/bin/bash

X2GoThinClientConfig ()
{

# Output startup message
#
echo -n " x2gothinclientconfig"

sed -i -e '\#<applications>#a<application title="X2Go Client" type="normal">' -e '\#<applications>#a<decor>no</decor>' -e '\#<applications>#a</application>' /etc/xdg/openbox/rc.xml

cat >/home/user/.xsession <<XSESSION
# inspired by 
# http://code.x2go.org/gitweb?p=x2gothinclient.git;a=blob_plain;f=displaymanager/sbin/x2gothinclientd;h=6897d42d17bd6778e7de5e62ec3f51727d4e8800;hb=HEAD
# check the above file for ideas before reinventing the wheel

# Spawn PulseAudio
ps -C pulseaudio --no-headers || (su - user -c "pulseaudio -D -n -L 'module-native-protocol-tcp port=4713' -L 'module-udev-detect' --exit-idle-time=65535")&

# Spawn openbox
openbox &

# Spawn X2GoClient
x2goclient --thinclient --no-session-edit --no-menu --maximize --add-to-known-hosts --haltbt --session-conf=/etc/x2go/x2gothinclient_sessions
XSESSION

chown user:user /home/user/.xsession
chmod 644 /home/user/.xsession

# Set Audio Volume
amixer -q sset Master 100
amixer -q sset PCM 100

}

X2GoThinClientConfig
