#!/bin/bash

X2GoThinClientConfig ()
{

# Output startup message
#
echo -n " x2go-thinclientconfig"

# using xmlstarlet would mean wasting yet another Megabyte of space ...
# disable virtual desktops
sed -i -e 's#<number>4</number>#<number>1</number>#' /etc/xdg/openbox/rc.xml
# disable OpenBox keyboard bindings
# this also disables the context menu (would be accessible in xinerama) and things like Alt-F4 for X2GoClient, Xephyr, etc.
sed -i -e '/<keyboard>/,/<\/keyboard>/{//!d}' /etc/xdg/openbox/rc.xml
sed -i -e '\#<action name="ShowMenu"><menu>[a-z-]*-menu</menu></action>#d' /etc/xdg/openbox/rc.xml
# make sure OpenBox maximizes X2GoClient on launch and hides window decorations
sed -i -e '\#<applications>#a<application title="X2Go Client" type="normal">' -e '\#<applications>#a<decor>no</decor>' -e '\#<applications>#a</application>' /etc/xdg/openbox/rc.xml
#make sure OpenBox' ToggleMaximize is disabled, or else clicking the top row of pixels will un-maximize X2GoClient
sed -i -e '/ToggleMaximize/d' /etc/xdg/openbox/rc.xml

cat >/home/user/.xsession <<XSESSION
# inspired by 
# http://code.x2go.org/gitweb?p=x2gothinclient.git;a=blob_plain;f=displaymanager/sbin/x2gothinclientd;h=6897d42d17bd6778e7de5e62ec3f51727d4e8800;hb=HEAD
# check the above file for ideas before reinventing the wheel

# Spawn PulseAudio
pulseaudio -D -n -L 'module-native-protocol-tcp port=4713' -L 'module-udev-detect' --exit-idle-time=65535 &

# additional variable instead of "case \$(...) in", as we need the value again later on
XRANDRCMDTAINTED=\$(cat /proc/cmdline | sed -e 's/ \([^ ]*\)=/\n\1=/g' | awk -F '=' '\$1 == "xinerama" { print \$2 }')

# sanitize input
case \$XRANDRCMDTAINTED in
"above")
	XRANDRCMD="above"
	;;
"below")
	XRANDRCMD="below"
	;;
"same-as")
	XRANDRCMD="same-as"
	;;
"right-of")
	XRANDRCMD="right-of"
	;;
*)
	XRANDRCMD="left-of" # default
	;;
esac

# find out how many touch devices we have
TOUCHDEVICESCOUNT=\$(LANG=C xsetwacom --list devices | wc -l)

# find out how many mouse devices we have
MICECOUNT=\$(find /dev/input -maxdepth 1 -name "mouse*" | wc -l)

# loop through the following code block for all connected display devices
for NEXT_DISPLAY in \$(LANG=C xrandr 2>/dev/null | grep ' connected ' | cut -d ' ' -f1); do

	#remove trailing newline from NEXT_DISPLAY
	NEXT_DISPLAY=\${NEXT_DISPLAY%\$'\n'}

	# THIS_DISPLAY won't be defined until the second time the loop is executed, which is a
	# neat way of running xrandr only if there are at least two connected display devices
	if [ -n "\${THIS_DISPLAY+x}" ] ; then

		if [ \$TOUCHDEVICESCOUNT -gt 0 ] &&  [ \$MICECOUNT -lt 1 ] && [ -z \$XRANDRCMDTAINTED ]; then
			# we have a touch device and no mice, and no xinerama parameter was set,
			# so switch to clone view to make the touch device usable
			/usr/bin/xrandr --output \$NEXT_DISPLAY --same-as \$THIS_DISPLAY

		else
			# else use whatever is in XRANDRCMD (which is either our default of "left-of",
			# or a valid xinerama kernel parameter value)
			/usr/bin/xrandr --output \$NEXT_DISPLAY --\$XRANDRCMD \$THIS_DISPLAY
		fi

	fi
	# now set THIS_DISPLAY -> every subsequent iteration of the loop will now enter the code block
	# above where [ -n \${THIS_DISPLAY+x} ] is the conditional
	THIS_DISPLAY=\$NEXT_DISPLAY
done

# Spawn openbox
openbox &

# set screen background to X2Go default blue on all detected screens
xsetroot -solid "#246ed8"

# Get X2GoConfig
BROKERURL=\$(cat /proc/cmdline | \
	    sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
	    awk -F'=' ' /^broker-url=/ { print \$2 }' | \
	    tr -dc 'a-zA-Z0-9.:/?%_\-')
SESSIONSELECT=\$(cat /proc/cmdline | \
	    sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
	    awk -F'=' ' /^session=/ { print \$2 }' | \
	    tr -dc 'a-zA-Z0-9.:/ _\-')
LDAP=\$(cat /proc/cmdline | \
	    sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
	    sed 's/^ldap=/ldap#/' | \
	    awk -F'#' ' /^ldap#/ { print \$2 }' | \
	    tr -dc 'a-zA-Z0-9.:_\-')
LDAP1=\$(cat /proc/cmdline | \
	    sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
	    sed 's/^ldap1=/ldap1#/' | \
	    awk -F'#' ' /^ldap1#/ { print \$2 }' | \
	    tr -dc 'a-zA-Z0-9.:_\-')
LDAP2=\$(cat /proc/cmdline | \
	    sed -e 's/ \([^ ]*\)=/\n\1=/g' | \
	    sed 's/^ldap2=/ldap2#/' | \
	    awk -F'#' ' /^ldap2#/ { print \$2 }' | \
	    tr -dc 'a-zA-Z0-9.:_\-')


# Check for background and branding SVGs
BRANDING=''
if grep -q ' branding=' /proc/cmdline; then
	while ! [ -s /etc/x2go/branding.svg ]; do
		OLDCON=\$(fgconsole)
		chvt 1
	        echo "'\$0' is waiting for a valid '/etc/x2go/branding.svg' file."
		sleep 2
	done
	[ -n "\$OLDCON" ] && chvt \$OLDCON
	BRANDING='--branding=/etc/x2go/branding.svg'
fi
BACKGROUND=''
if grep -q ' bg=' /proc/cmdline; then
	while ! [ -s /etc/x2go/bg.svg ]; do
		OLDCON=\$(fgconsole)
		chvt 1
	        echo "'\$0' is waiting for a valid '/etc/x2go/bg.svg' file."
		sleep 2
	done
	[ -n "\$OLDCON" ] && chvt \$OLDCON
	BACKGROUND='--background=/etc/x2go/bg.svg'
fi

# Spawn X2GoClient
if [ -n "\$SESSIONSELECT" ]; then
	STARTSESSION="--session='\$SESSIONSELECT'"
fi
if [ -n "\$BROKERURL" ]; then
	SESSIONFROM="--broker-url=\$BROKERURL"
else 
	SESSIONFROM="--session-conf=/etc/x2go/x2gothinclient_sessions"
	while ! [ -s /etc/x2go/x2gothinclient_sessions ]; do
		OLDCON=\$(fgconsole)
		chvt 1
	        echo "'\$0' is waiting for a valid '/etc/x2go/x2gothinclient_sessions' file."
		sleep 2
	done
	[ -n "\$OLDCON" ] && chvt \$OLDCON
fi
if [ -n "\$LDAP" ] ; then
	if [ -n "\$LDAP1" ] ; then
		BACKUPLDAP="--ldap1=\$LDAP1"
		if [ -n "\$LDAP2" ] ; then
			BACKUPLDAP="\$BACKUPLDAP --ldap2=\$LDAP2"
		fi
	fi
	LDAPPARAMS="--ldap=\$LDAP \$BACKUPLDAP"
else
	LDAPPARAMS=""
fi

BLANKINGTIME=\$(cat /proc/cmdline | sed -e 's/ \([^ ]*\)=/\n\1=/g' | awk -F '=' '\$1 == "blank" { print \$2 }' | tr -dc '0-9:')
if [ -n "\$BLANKINGTIME" ]; then
	DPMSARR=(\$(echo \$BLANKINGTIME | awk -F ':' '\$1 ~/^[0-9]*\$/ && \$2 ~/^[0-9]*\$/ && \$3 ~/^[0-9]*\$/  { print \$1 " " \$2 " " \$3}'))
	if [ \${DPMSARR[0]} -eq 0 ]; then
		# Disable screensaver and DPMS Power Saving if requested
		xset s off
		if ! grep -q '\W*nodpms\W*' /proc/cmdline; then
			xset -dpms
		fi
	else
		xset s on
		xset s \${DPMSARR[0]}
		if ! grep -q '\W*nodpms\W*' /proc/cmdline; then
			# Yes, "+dpms dpms" is intentional. 
			xset +dpms dpms \${DPMSARR[0]} \${DPMSARR[1]} \${DPMSARR[2]}
		fi
	fi
fi

eval x2goclient --thinclient --no-session-edit --no-menu --maximize --add-to-known-hosts --haltbt --read-exports-from=/home/user/export \$LDAPPARAMS \$SESSIONFROM \$BACKGROUND \$BRANDING \$STARTSESSION
XSESSION

chown user:user /home/user/.xsession
chmod 644 /home/user/.xsession

# This is needed for File Sharing support (USB media and the like)
mkdir -p /home/user/{export,logins,mounts}
chown user:user /home/user/{export,logins,mounts}
chmod 700 /home/user/{export,logins,mounts}

}

X2GoThinClientConfig
