#!/bin/sh

function urldecode() {
	        : "${*//+/ }"; echo -e "${_//%/\\x}";
	}

FirefoxConfig ()
{
	# Output startup message
	#
	echo -n " firefoxconfig"

	HOMEPAGEURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
		      awk -F'=' ' /^homepageurl=/ { print $2 } ')
	if [ -z "$HOMEPAGEURL" ] ; then 
		HOMEPAGEURL='http://www.x2go.org/'
	else
		HOMEPAGEURL=$(echo -e "$(urldecode "$HOMEPAGEURL")")
	fi
	sed -i	-e '/"browser.rights.3.shown"/d' \
		-e '/"browser.startup.homepage_override.mstone"/d' \
		-e '/"browser.startup.homepage"/d' \
		/etc/firefox-esr/firefox-esr.js
	cat >>/etc/firefox-esr/firefox-esr.js <<FIREFOXCONFIG

//set some sane browser defaults
lockPref("browser.newtabpage.activity-stream.aboutHome.enabled", false); 
lockPref("datareporting.policy.firstRunURL", ""); 
lockPref("privacy.donottrackheader.enabled", true);
lockPref("browser.rights.3.shown", true);
lockPref("browser.startup.homepage_override.mstone","ignore");
lockPref("browser.startup.homepage", "$HOMEPAGEURL");
FIREFOXCONFIG
}

FirefoxConfig
