#!/bin/bash

X2GoThinClientConfig ()
{

# Output startup message
#
echo -n " x2go-thinclientconfig"

# using xmlstarlet would mean wasting yet another Megabyte of space ...
# disable virtual desktops
sed -i -e 's#<number>4</number>#<number>1</number>#' /etc/xdg/openbox/rc.xml
# disable OpenBox keyboard bindings
# this also disables the context menu (would be accessible in xinerama) and things like Alt-F4 for X2GoClient, Xephyr, etc.
sed -i -e '/<keyboard>/,/<\/keyboard>/{//!d}' /etc/xdg/openbox/rc.xml
sed -i -e '\#<action name="ShowMenu"><menu>[a-z-]*-menu</menu></action>#d' /etc/xdg/openbox/rc.xml
# make sure OpenBox maximizes X2GoClient on launch and hides window decorations
sed -i -e '\#<applications>#a<application title="X2Go Client" type="normal">' -e '\#<applications>#a<decor>no</decor>' -e '\#<applications>#a</application>' /etc/xdg/openbox/rc.xml
#make sure OpenBox' ToggleMaximize is disabled, or else clicking the top row of pixels will un-maximize X2GoClient
sed -i -e '/ToggleMaximize/d' /etc/xdg/openbox/rc.xml

# This is needed for File Sharing support (USB media and the like)
mkdir -p /home/user/{export,logins,mounts}
chown user:user /home/user/{export,logins,mounts}
chmod 700 /home/user/{export,logins,mounts}

}

X2GoThinClientConfig
