#!/bin/bash
export TERM=linux;
BRANDINGURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
	      awk -F'=' ' /^branding=/ { print $2 }' | \
	      tr -dc 'a-zA-Z0-9.:/?%_\-')
BRANDINGDESTINATION=/etc/x2go/branding.svg

if [ -n "$BRANDINGURL" ] ; then

	if [ "$METHOD" = "loopback" ] || [ "$METHOD" = "none" ]; then
		exit 0
	fi

	(
		while ! [ -c /dev/tty8 ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for tty8 to become available."
			sleep 2
		done
		while [ -z "$(hostname -I)" ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for a client IP." | tee -a /dev/tty8
			sleep 2
		done

		echo -en "\n$(date +'%F | %T | ')'$0': Attempting branding SVG download ..." | tee -a /dev/tty8
		if echo "$BRANDINGURL" | grep -q "^tftp://" ; then
			BRANDINGSERVER=$(echo "$BRANDINGURL" | sed 's#^tftp://\([^/]*\)/.*$#\1#' )
			BRANDINGPATH=$(echo "$BRANDINGURL" | sed 's#^tftp://[^/]*/\(.*\)$#\1#' )
			if [ -n "$BRANDINGSERVER" ] && [ -n "$BRANDINGPATH" ] ; then
				while ! atftp "$BRANDINGSERVER" -g -r "$BRANDINGPATH" -l ${BRANDINGDESTINATION}.tmp ; do
					echo -en "\n$(date +'%F | %T | ')still waiting for branding SVG download (tftp) ..." | tee -a /dev/tty8
					sleep 5
				done
			fi
		else
			while ! wget -q -O ${BRANDINGDESTINATION}.tmp "$BRANDINGURL" ; do
				echo -en "\n$(date +'%F | %T | ')still waiting for branding SVG download (wget) ..." | tee -a /dev/tty8
				sleep 5 
			done
		fi

		echo -en "\n$(date +'%F | %T | ')'$0': branding SVG download complete." | tee -a /dev/tty8
		if [ -s ${BRANDINGDESTINATION}.tmp ] ; then
			mv ${BRANDINGDESTINATION}.tmp $BRANDINGDESTINATION
			ln $BRANDINGDESTINATION /etc/x2go/x2gothinclient_branding.svg
			if [ -s /etc/x2go/x2gothinclient-minidesktop_start ] ; then
				if ! grep -q -- "--branding" /etc/x2go/x2gothinclient-minidesktop_start ; then
					sed -e '\#^/usr/lib/x2go/x2goclient#a \\t\t\t --branding="/etc/x2go/x2gothinclient_branding.svg" \\' -i /etc/x2go/x2gothinclient-minidesktop_start
				fi
			fi
		fi
	) &
fi
