#!/bin/bash
export TERM=linux;
BGURL=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | \
	awk -F'=' ' /^bg=/ { print $2 }' | \
	tr -dc 'a-zA-Z0-9.:/?%_\-')
BGDESTINATION=/etc/x2go/bg.svg

if [ -n "$BGURL" ] ; then

	if [ "$METHOD" = "loopback" ] || [ "$METHOD" = "none" ]; then
		exit 0
	fi

	(
		while ! [ -c /dev/tty8 ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for tty8 to become available."
			sleep 2
		done
		while [ -z "$(hostname -I)" ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for a client IP." | tee -a /dev/tty8
			sleep 2
		done

		echo -en "\n$(date +'%F | %T | ')'$0': Attempting background SVG download ..." | tee -a /dev/tty8
		if echo "$BGURL" | grep -q "^tftp://" ; then
			BGSERVER=$(echo "$BGURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
			BGPATH=$(echo "$BGURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
			if [ -n "$BGSERVER" ] && [ -n "$BGPATH" ] ; then
				while ! atftp "$BGSERVER" -g -r "$BGPATH" -l ${BGDESTINATION}.tmp ; do
					echo -en "\n$(date +'%F | %T | ')still waiting for background SVG download (tftp) ..." | tee -a /dev/tty8
					sleep 5
				done
			fi
		else
			while ! wget -q -O ${BGDESTINATION}.tmp "$BGURL" ; do
				echo -en "\n$(date +'%F | %T | ')still waiting for background SVG download (wget) ..." | tee -a /dev/tty8
				sleep 5 
			done
		fi

		echo -en "\n$(date +'%F | %T | ')'$0': background SVG download complete." | tee -a /dev/tty8
		if [ -s ${BGDESTINATION}.tmp ] ; then
			mv ${BGDESTINATION}.tmp $BGDESTINATION
			ln $BGDESTINATION /etc/x2go/x2gothinclient_bg.svg
			if [ -s /etc/x2go/x2gothinclient-minidesktop_start ] ; then
				if ! grep -q -- "--background" /etc/x2go/x2gothinclient-minidesktop_start ; then
					sed -e '\#^/usr/lib/x2goclient#a \\t\t\t --background="/etc/x2go/x2gothinclient_bg.svg" \\' -i /etc/x2go/x2gothinclient-minidesktop_start
				fi
			fi
		fi
	) &
fi
