#!/bin/bash
export TERM=linux;
XROOT=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | awk -F '=' '$1 == "xroot" { print $2 }' | tr -dc '0-9a-zA-Z,$-_.+!*'"'"'();/?:@=&|')
IMAGEDIR=/var/tmp/images/
mkdir -p $IMAGEDIR/background

if [ -n "$XROOT" ] ; then

	if [ "$METHOD" = "loopback" ] || [ "$METHOD" = "none" ]; then
		exit 0
	fi

	(
		while ! [ -c /dev/tty8 ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for tty8 to become available."
			sleep 2
		done
		while [ -z "$(hostname -I)" ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for a client IP." | tee -a /dev/tty8
			sleep 2
		done

		echo -en "\n$(date +'%F | %T | ')'$0': Attempting X background download ..." | tee -a /dev/tty8
		if echo "$XROOT" | grep -q "^tftp://" ; then
			for SINGLEURL in ${XROOT//|/ }; do
				XROOTSERVER=$(echo "$SINGLEROOT" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
				XROOTPATH=$(echo "$SINGLEROOT" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
				if [ -n "$XROOTSERVER" ] && [ -n "$XROOTPATH" ] ; then
					while ! (cd ${IMAGEDIR}/background/ && atftp "$XROOTSERVER" -g -r "$XROOTPATH") ; do
						echo -en "\n$(date +'%F | %T | ')still waiting for X background download (tftp) ..." | tee -a /dev/tty8
						sleep 5
					done
				fi
			done
		elif echo "$XROOT" | grep -q "^://" ; then
			while ! wget -q -N -P $IMAGEDIR/background ${XROOT//|/ } ; do
				echo -en "\n$(date +'%F | %T | ')still waiting for X background download (wget) ..." | tee -a /dev/tty8
				sleep 5 
			done
		else
			: # NOP
		fi

		echo -en "\n$(date +'%F | %T | ')'$0': X background download complete." | tee -a /dev/tty8
	) &
fi
