#!/bin/bash
export TERM=linux;
XSAVERIMAGES=$(sed -e 's/ \([^ ]*\)=/\n\1=/g' -e 's/\([^=]["'"'"']\) /\1\n/g' -e 's/ \([^ "'"'"']\)/\n\1/g' /proc/cmdline | awk -F '=' '$1 == "xsaverimages" { print $2 }' | tr -dc '0-9a-zA-Z,$-_.+!*'"'"'();/?:@=&|')

IMAGEDIR=/var/tmp/images/
SLIDESDIR="${IMAGEDIR}/slides/"

# if we're a MATE-MiniDesktop, let this be our homedirectory
USERHOME=$(getent passwd x2gothinclient | awk -F':' '{ print $6 }')
# No Match? Then we're a regular TCE-Live.
if [ -z "$USERHOME" ] ; then
	USERHOME=$(getent passwd 1000 | awk -F':' '{ print $6 }')
else
		# if this is MMD, create a directory for MATE's
		# braindead slideshow screensaver that doesn't allow you to
		# specify an image directory
		mkdir -p ${USERHOME}/Pictures
fi

function urldecode() { 
	: "${*//+/ }"; echo -e "${_//%/\\x}"; 
}

mkdir -p $SLIDESDIR

if [ -n "$XSAVERIMAGES" ] ; then

	if [ "$METHOD" = "loopback" ] || [ "$METHOD" = "none" ]; then
		exit 0
	fi

	(
		while ! [ -c /dev/tty8 ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for tty8 to become available."
			sleep 2
		done
		while [ -z "$(hostname -I)" ] ; do
			echo -en "\n$(date +'%F | %T | ')'$0' is waiting for a client IP." | tee -a /dev/tty8
			sleep 2
		done

		echo -en "\n$(date +'%F | %T | ')'$0': Attempting screensaver image/images download ..." | tee -a /dev/tty8
		XSAVERIMAGES=$(echo -e "$(urldecode "$XSAVERIMAGES")")
		if echo "$XSAVERIMAGES" | grep -q "^tftp://" ; then
			for SINGLEXSAVERIMAGEURL in ${XSAVERIMAGES//|/ }; do
				XSAVERIMAGESERVER=$(echo "$SINGLEXSAVERIMAGEURL" | sed 's#^tftp://\([^/;]*\)/.*$#\1#' )
				XSAVERIMAGEPATH=$(echo "$SINGLEXSAVERIMAGEURL" | sed 's#^tftp://[^/;]*/\([^;]*\)$#\1#' )
				if [ -n "$XSAVERIMAGESERVER" ] && [ -n "$XSERVERIMAGEPATH" ] ; then
					while ! (cd $SLIDESDIR && atftp "$XSAVERIMAGESERVER" -g -r "$XSAVERIMAGEPATH") ; do
						echo -en "\n$(date +'%F | %T | ')still waiting for screensaver download (tftp) ..." | tee -a /dev/tty8
						sleep 5
					done
				fi
			done
		elif echo "$XSAVERIMAGES" | grep -q "://" ; then
			while ! wget -q -N -P $SLIDESDIR ${XSAVERIMAGES//|/ } ; do
				echo -en "\n$(date +'%F | %T | ')still waiting for screensaver download (wget) ..." | tee -a /dev/tty8
				sleep 5 
			done
		else
			: # NOP
		fi

		# If this directory exists, then we're a MMD and images need to go there.  Hardlinking them to save space.
		[ -d ${USERHOME}/Pictures ] && cp -al ${SLIDESDIR}/* ${USERHOME}/Pictures

		echo -en "\n$(date +'%F | %T | ')'$0': Screensaver download complete." | tee -a /dev/tty8

	) &
fi
